server:
  port: 8093

spring:
  application:
    name: service-hi
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://192.168.1.132:3306/guazi?useUnicode=true&characterEncoding=utf-8
    username: root
  main:
      allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#\u2191\u58F0\u660E\u7684\u662F\u670D\u52A1\u540D\u79F0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
mybatis:
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000


